let databaseProdutosDestaque = [
   {
      id: "f1",
      marca: "adidas",
      nome: "Camisa Astronaut",
      preco: 79.95,
      img: "assets/img/products/f1.jpg",
   },
   {
      id: "f2",
      marca: "adidas",
      nome: "Camisa Astronaut",
      preco: 79.95,
      img: "assets/img/products/f2.jpg",
   },
   {
      id: "f3",
      marca: "nike",
      nome: "Camisa Astronaut",
      preco: 79.95,
      img: "assets/img/products/f3.jpg",
   },
   {
      id: "f4",
      marca: "puma",
      nome: "Camisa Astronaut",
      preco: 79.95,
      img: "assets/img/products/f4.jpg",
   },
   {
      id: "f5",
      marca: "adidas",
      nome: "Camisa Astronaut",
      preco: 79.95,
      img: "assets/img/products/f5.jpg",
   },
   {
      id: "f6",
      marca: "nike",
      nome: "Camisa Astronaut",
      preco: 79.95,
      img: "assets/img/products/f6.jpg",
   },
   {
      id: "f7",
      marca: "puma",
      nome: "Camisa Astronaut",
      preco: 79.95,
      img: "assets/img/products/f7.jpg",
   },
   {
      id: "f8",
      marca: "converse",
      nome: "Camisa Astronaut",
      preco: 79.95,
      img: "assets/img/products/f8.jpg",
   },
];
let databaseProdutosNovos = [
   {
      id: "n1",
      marca: "adidas",
      nome: "Camisa Astronaut",
      preco: 79.95,
      img: "assets/img/products/n1.jpg",
   },
   {
      id: "n2",
      marca: "adidas",
      nome: "Camisa Astronaut",
      preco: 79.95,
      img: "assets/img/products/n2.jpg",
   },
   {
      id: "n3",
      marca: "nike",
      nome: "Camisa Astronaut",
      preco: 79.95,
      img: "assets/img/products/n3.jpg",
   },
   {
      id: "n4",
      marca: "puma",
      nome: "Camisa Astronaut",
      preco: 79.95,
      img: "assets/img/products/n4.jpg",
   },
   {
      id: "n5",
      marca: "adidas",
      nome: "Camisa Astronaut",
      preco: 79.95,
      img: "assets/img/products/n5.jpg",
   },
   {
      id: "n6",
      marca: "nike",
      nome: "Camisa Astronaut",
      preco: 79.95,
      img: "assets/img/products/n6.jpg",
   },
   {
      id: "n7",
      marca: "puma",
      nome: "Camisa Astronaut",
      preco: 79.95,
      img: "assets/img/products/n7.jpg",
   },
   {
      id: "n8",
      marca: "converse",
      nome: "Camisa Astronaut",
      preco: 79.95,
      img: "assets/img/products/n8.jpg",
   },
];

let databaseProdutos = [
   {
      id: "f1",
      marca: "adidas",
      nome: "Camisa Astronaut",
      preco: 79.95,
      img: "assets/img/products/f1.jpg",
   },
   {
      id: "f2",
      marca: "adidas",
      nome: "Camisa Astronaut",
      preco: 79.95,
      img: "assets/img/products/f2.jpg",
   },
   {
      id: "f3",
      marca: "nike",
      nome: "Camisa Astronaut",
      preco: 79.95,
      img: "assets/img/products/f3.jpg",
   },
   {
      id: "f4",
      marca: "puma",
      nome: "Camisa Astronaut",
      preco: 79.95,
      img: "assets/img/products/f4.jpg",
   },
   {
      id: "f5",
      marca: "adidas",
      nome: "Camisa Astronaut",
      preco: 79.95,
      img: "assets/img/products/f5.jpg",
   },
   {
      id: "f6",
      marca: "nike",
      nome: "Camisa Astronaut",
      preco: 79.95,
      img: "assets/img/products/f6.jpg",
   },
   {
      id: "f7",
      marca: "puma",
      nome: "Camisa Astronaut",
      preco: 79.95,
      img: "assets/img/products/f7.jpg",
   },
   {
      id: "f8",
      marca: "converse",
      nome: "Camisa Astronaut",
      preco: 79.95,
      img: "assets/img/products/f8.jpg",
   },
   {
      id: "n1",
      marca: "adidas",
      nome: "Camisa Astronaut",
      preco: 79.95,
      img: "assets/img/products/n1.jpg",
   },
   {
      id: "n2",
      marca: "adidas",
      nome: "Camisa Astronaut",
      preco: 79.95,
      img: "assets/img/products/n2.jpg",
   },
   {
      id: "n3",
      marca: "nike",
      nome: "Camisa Astronaut",
      preco: 79.95,
      img: "assets/img/products/n3.jpg",
   },
   {
      id: "n4",
      marca: "puma",
      nome: "Camisa Astronaut",
      preco: 79.95,
      img: "assets/img/products/n4.jpg",
   },
   {
      id: "n5",
      marca: "adidas",
      nome: "Camisa Astronaut",
      preco: 79.95,
      img: "assets/img/products/n5.jpg",
   },
   {
      id: "n6",
      marca: "nike",
      nome: "Camisa Astronaut",
      preco: 79.95,
      img: "assets/img/products/n6.jpg",
   },
   {
      id: "n7",
      marca: "puma",
      nome: "Camisa Astronaut",
      preco: 79.95,
      img: "assets/img/products/n7.jpg",
   },
   {
      id: "n8",
      marca: "converse",
      nome: "Camisa Astronaut",
      preco: 79.95,
      img: "assets/img/products/n8.jpg",
   },
];
